// app/api/seed-linea/route.ts
// ONE-TIME seed with real public data about Linea Solutions.
// Call POST /api/seed-linea to populate. Safe to call again — uses upsert.

import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/db';

// ─── Real Clients (publicly confirmed) ───────────────────────────────────────

const REAL_CLIENTS = [
  { id: 'client-calstrs', name: 'California State Teachers\' Retirement System (CalSTRS)', industry: 'Public Pension', location: 'Sacramento, CA', size: 'Large', website: 'calstrs.com', notes: 'Active AI deployment and system implementation support. One of the largest US pension funds.' },
  { id: 'client-calpers', name: 'California Public Employees\' Retirement System (CalPERS)', industry: 'Public Pension', location: 'Sacramento, CA', size: 'Large', website: 'calpers.ca.gov', notes: 'Modernization assessment and strategic advisory.' },
  { id: 'client-sers-ohio', name: 'School Employees Retirement System of Ohio (SERS)', industry: 'Public Pension', location: 'Columbus, OH', size: 'Large', website: 'ohsers.org', notes: 'AI Strategic Advisory engagement; Nate Haws serving as AI Strategic Advisor.' },
  { id: 'client-nycppf', name: 'New York City Police Pension Fund (NYCPPF)', industry: 'Public Pension', location: 'New York, NY', size: 'Large', website: 'nyc.gov/nycppf', notes: 'System implementation support.' },
  { id: 'client-vrs', name: 'Virginia Retirement System (VRS)', industry: 'Public Pension', location: 'Richmond, VA', size: 'Large', website: 'varetire.org', notes: 'Data profiling, conversion, and reconciliation via ICON.' },
  { id: 'client-ucrs', name: 'University of California Retirement System (UCRS)', industry: 'Public Pension', location: 'Oakland, CA', size: 'Large', website: 'ucop.edu', notes: 'Data profiling, cleansing, and migration via ICON.' },
  { id: 'client-ipers', name: 'Iowa Public Employees\' Retirement System (IPERS)', industry: 'Public Pension', location: 'Des Moines, IA', size: 'Medium', website: 'ipers.org', notes: 'Data quality and conversion project via ICON.' },
  { id: 'client-apers', name: 'Arkansas Public Employees Retirement System (APERS)', industry: 'Public Pension', location: 'Little Rock, AR', size: 'Medium', website: 'apers.org', notes: 'Data profiling, cleansing, and migration via ICON.' },
  { id: 'client-erfc', name: 'Educational Employees\' Supplementary Retirement System of Fairfax County (ERFC)', industry: 'Public Pension', location: 'Fairfax, VA', size: 'Small', website: 'erfc.net', notes: 'System implementation and AI chatbot development.' },
  { id: 'client-sc-peba', name: 'South Carolina Public Employee Benefit Authority (PEBA)', industry: 'Public Pension', location: 'Columbia, SC', size: 'Large', website: 'peba.sc.gov', notes: 'System implementation support.' },
  { id: 'client-city-la', name: 'City of Los Angeles', industry: 'Government / Benefits', location: 'Los Angeles, CA', size: 'Large', website: 'lacity.org', notes: '10+ year engagement across various benefit programs.' },
  { id: 'client-barbados-nlc', name: 'Barbados National Insurance Scheme', industry: 'Workers\' Compensation / Social Program', location: 'Bridgetown, Barbados', size: 'Medium', website: 'nis.gov.bb', notes: 'Social program modernization — international expansion engagement.' },
  { id: 'client-orpp', name: 'Ontario Retirement Pension Plan Authority (ORPP)', industry: 'Public Pension', location: 'Toronto, ON', size: 'Medium', website: 'orpp.ca', notes: 'Strategic guidance during initial formation phase (Canada expansion catalyst).' },
];

// ─── Real Employees (publicly confirmed from lineasolutions.com, lineasecure.com, ICON) ──

const REAL_EMPLOYEES = [
  // ── C-Suite / Executive ────────────────────────────────────────────────────
  {
    id: 'emp-akio-tagawa',
    name: 'Akio Tagawa',
    rampName: 'Tagawa, Akio',
    email: 'akio.tagawa@lineasolutions.com',
    companyGroup: 'Linea Solutions',
    businessUnit: 'Executive',
    careerPath: 'Management',
    roleFamily: 'Executive',
    practice: 'CrossPractice',
    level: 'Executive',
    title: 'Founder, President & CEO',
    location: 'US',
    resumeText: 'Akio Tagawa is the Founder, President & CEO of Linea Solutions with over 25 years in IT consulting. He specializes in organizational change management for retirement systems since 1998. A recognized thought leader who drove pension software vendors to adopt agile development methodologies (since 2010). Co-founded Linea Secure (2018) and co-owns ICON Integration & Design (since 2023). Regular conference speaker at NASRA, NIRS, ACPM. Board member: NASRA, KCRW, The Phillips Collection, ICA Los Angeles. Education: UCLA, Sophia University, University of Wisconsin-Madison.',
    extractedSkills: JSON.stringify(['Agile', 'Change Management', 'Pension Administration', 'AI Strategy', 'Vendor Selection', 'Organizational Leadership', 'Board Governance']),
  },
  {
    id: 'emp-rachel-comstock',
    name: 'Rachel Comstock',
    rampName: 'Comstock, Rachel',
    email: 'rachel.comstock@lineasolutions.com',
    companyGroup: 'Linea Solutions',
    businessUnit: 'Executive',
    careerPath: 'Management',
    roleFamily: 'Executive',
    practice: 'CrossPractice',
    level: 'Executive',
    title: 'Chief Delivery Officer',
    location: 'US',
    resumeText: 'Rachel Comstock is the Chief Delivery Officer at Linea Solutions, responsible for ensuring consistent, high-quality delivery across all engagements. Oversees delivery standards, methodologies, and practices across the consulting organization.',
    extractedSkills: JSON.stringify(['Delivery Management', 'Project Portfolio Management', 'Consulting Operations', 'Quality Assurance', 'Team Leadership']),
  },
  {
    id: 'emp-kimm-nasser-fenn',
    name: 'Kimm Nasser-Fenn',
    rampName: 'Nasser-Fenn, Kimm',
    email: 'kimm.nasserfenn@lineasolutions.com',
    companyGroup: 'Linea Solutions',
    businessUnit: 'Executive',
    careerPath: 'Management',
    roleFamily: 'Executive',
    practice: 'CrossPractice',
    level: 'Executive',
    title: 'Chief People Officer',
    location: 'US',
    resumeText: 'Kimm Nasser-Fenn is Chief People Officer and VP of Professional Development at Linea Solutions. Over 30 years of IT project/program management experience; 15 years specializing in pension administration system implementations. Former Practice Manager at IBM Global Services. Leads internal education, organizational change management practice, and staff professional development.',
    extractedSkills: JSON.stringify(['Organizational Change Management', 'OCM', 'Program Management', 'Pension Administration', 'Training', 'IBM', 'HR Leadership', 'Professional Development']),
  },
  {
    id: 'emp-kevin-lynch',
    name: 'Kevin Lynch',
    rampName: 'Lynch, Kevin',
    email: 'kevin.lynch@lineasolutions.com',
    companyGroup: 'Linea Solutions',
    businessUnit: 'Sales & Business Development',
    careerPath: 'Management',
    roleFamily: 'Business Development',
    practice: 'CrossPractice',
    level: 'Executive',
    title: 'Chief Sales Officer',
    location: 'US',
    resumeText: 'Kevin Lynch is Chief Sales Officer at Linea Solutions. Leads sales and client relationship strategy across pension, insurance, and workers\' compensation markets. Regular contributor to Linea thought leadership publications.',
    extractedSkills: JSON.stringify(['Sales Leadership', 'Client Relationship Management', 'Business Development', 'Pension', 'Insurance', 'Workers Compensation']),
  },
  {
    id: 'emp-bryce-haws',
    name: 'Bryce Haws',
    rampName: 'Haws, Bryce',
    email: 'bryce.haws@lineasolutions.com',
    companyGroup: 'Linea Solutions',
    businessUnit: 'Sales & Business Development',
    careerPath: 'Management',
    roleFamily: 'Business Development',
    practice: 'CrossPractice',
    level: 'SVP',
    title: 'SVP, Sales & Marketing',
    location: 'US',
    resumeText: 'Bryce Haws is SVP of Sales & Marketing at Linea Solutions and Linea Secure. Drives marketing strategy, brand awareness, and sales growth across the full Linea family of companies. Conference speaker at NASRA Winter Meeting.',
    extractedSkills: JSON.stringify(['Sales', 'Marketing', 'Brand Strategy', 'Business Development', 'Conference Speaking', 'Pension', 'Cybersecurity']),
  },
  // ── VPs / Senior Leadership ───────────────────────────────────────────────
  {
    id: 'emp-lon-tiggelaar',
    name: 'Lon Tiggelaar',
    rampName: 'Tiggelaar, Lon',
    email: 'lon.tiggelaar@lineasolutions.com',
    companyGroup: 'Linea Solutions',
    businessUnit: 'Delivery',
    careerPath: 'Consultant',
    roleFamily: 'Project Manager',
    practice: 'Insurance',
    level: 'SVP',
    title: 'SVP, Insurance Practice Leader',
    location: 'US',
    resumeText: 'Lon Tiggelaar is SVP and Insurance Practice Leader at Linea Solutions, based in Sioux Falls, SD. Over 25 years in insurance, pension, and benefits. Led large transformation projects with teams of 100+ staff across three continents. Former Public Retirement and Unemployment Insurance Practice Leader at a publicly held systems integrator. Former VP of Project Development in private equity. Former Board Member of the Sioux Falls City Employees\' Retirement System. Conference speaker at LIMRA Enrollment Technology Strategy Seminar.',
    extractedSkills: JSON.stringify(['Insurance', 'Pension', 'Program Management', 'Transformation', 'Vendor Selection', 'Multi-continental Delivery', 'Private Equity', 'Agile']),
  },
  {
    id: 'emp-vickie-kennedy',
    name: 'Vickie Kennedy',
    rampName: 'Kennedy, Vickie',
    email: 'vickie.kennedy@lineasolutions.com',
    companyGroup: 'Linea Solutions',
    businessUnit: 'Delivery',
    careerPath: 'Consultant',
    roleFamily: 'Consultant',
    practice: 'Workers Compensation',
    level: 'VP',
    title: 'Vice President, Workers\' Compensation',
    location: 'US',
    resumeText: 'Vickie Kennedy is VP of Workers\' Compensation at Linea Solutions (joined April 2022). Over 50 years of experience in workers\' compensation. Former Assistant Director for Insurance Services at Washington State Department of Labor and Industries (L&I) for 9 years. Former Chief Policy Advisor at L&I. Awards: IAIABC Frances Perkins Award, WorkCompCentral Comp Laude Award, Washington Governor\'s Distinguished Manager Award.',
    extractedSkills: JSON.stringify(['Workers Compensation', 'Policy', 'Government', 'Claims Administration', 'Insurance Services', 'Regulatory Affairs', 'Program Leadership']),
  },
  {
    id: 'emp-jason-todd',
    name: 'Jason Todd',
    rampName: 'Todd, Jason',
    email: 'jason.todd@lineasecure.com',
    companyGroup: 'Linea Secure',
    businessUnit: 'Cyber',
    careerPath: 'Specialist',
    roleFamily: 'Cybersecurity',
    practice: 'Cybersecurity',
    level: 'VP',
    title: 'VP, Cybersecurity & Data Solutions',
    location: 'US',
    resumeText: 'Jason Todd is VP of Cybersecurity & Data Solutions, spanning both Linea Solutions and Linea Secure. Leads cybersecurity sales and client engagements for pension and benefits organizations. Brings deep expertise in security assessments, data protection, and cloud security.',
    extractedSkills: JSON.stringify(['Cybersecurity', 'Data Security', 'Cloud Security', 'Penetration Testing', 'Sales', 'Pension Cybersecurity', 'Risk Assessment']),
  },
  {
    id: 'emp-mary-anne-walker',
    name: 'Mary Anne Walker',
    rampName: 'Walker, Mary Anne',
    email: 'maryanne.walker@lineasolutions.com',
    companyGroup: 'Linea Solutions',
    businessUnit: 'Delivery',
    careerPath: 'Management',
    roleFamily: 'Project Manager',
    practice: 'CrossPractice',
    level: 'VP',
    title: 'Vice President, Consulting Services',
    location: 'Canada',
    resumeText: 'Mary Anne Walker is Vice President of Consulting Services at Linea Solutions, based in Canada. Oversees consulting delivery for Canadian client engagements, supporting pension and benefits organizations across the country.',
    extractedSkills: JSON.stringify(['Consulting Services', 'Delivery Management', 'Pension', 'Benefits', 'Canada', 'Client Management', 'Team Leadership']),
  },
  // ── Directors ─────────────────────────────────────────────────────────────
  {
    id: 'emp-kim-zierath',
    name: 'Kim Zierath',
    rampName: 'Zierath, Kim',
    email: 'kim.zierath@lineasolutions.com',
    companyGroup: 'Linea Solutions',
    businessUnit: 'Delivery',
    careerPath: 'Consultant',
    roleFamily: 'Project Manager',
    practice: 'CrossPractice',
    level: 'Director',
    title: 'Senior Director, Implementation Consulting',
    location: 'US',
    resumeText: 'Kim Zierath is Senior Director of Implementation Consulting at Linea Solutions with 15+ years at the firm. PMP and ACP certified. Experienced in pension, workers\' compensation, and claims core system replacement projects. Leads complex multi-year implementation engagements.',
    extractedSkills: JSON.stringify(['PMP', 'ACP', 'Project Management', 'Pension Administration', 'Workers Compensation', 'System Implementation', 'Agile', 'Core System Replacement']),
  },
  {
    id: 'emp-ryan-guppy',
    name: 'Ryan Guppy',
    rampName: 'Guppy, Ryan',
    email: 'ryan.guppy@lineasolutions.com',
    companyGroup: 'Linea Solutions',
    businessUnit: 'Delivery',
    careerPath: 'Consultant',
    roleFamily: 'Consultant',
    practice: 'Workers Compensation',
    level: 'Director',
    title: 'Director, Work Disability Prevention',
    location: 'US',
    resumeText: 'Ryan Guppy is Director of Work Disability Prevention at Linea Solutions (joined April 2022). Nearly 20 years in workers\' compensation specializing in vocational rehabilitation and return to work. Certified Disability Management Specialist (CDMS). Past President, International Association of Rehabilitation Professionals - Washington Chapter. 2017 Washington Governor\'s Leadership in Management Award.',
    extractedSkills: JSON.stringify(['Workers Compensation', 'Vocational Rehabilitation', 'Return to Work', 'CDMS', 'Disability Management', 'Policy', 'Program Management']),
  },
  {
    id: 'emp-vincent-houle',
    name: 'Vincent Houle',
    rampName: 'Houle, Vincent',
    email: 'vincent.houle@lineasolutions.com',
    companyGroup: 'Linea Solutions ULC',
    businessUnit: 'Delivery',
    careerPath: 'Consultant',
    roleFamily: 'Business Analyst',
    practice: 'Pension',
    level: 'Associate Principal',
    title: 'Director, RAMP Program & Associate Principal Consultant',
    location: 'Canada',
    resumeText: 'Vincent Houle is the Director of the Resource Allocation Management Program (RAMP) and an Associate Principal Consultant at Linea Solutions ULC (Canada). Leads internal resource allocation and workforce management initiatives. Also listed as Senior Consultant at Linea Secure, supporting cybersecurity engagements for Canadian pension clients.',
    extractedSkills: JSON.stringify(['Resource Management', 'Program Management', 'Pension', 'Cybersecurity', 'Business Analysis', 'Canada', 'RAMP', 'Workforce Planning']),
  },
  // ── Principal / Senior Consultants ────────────────────────────────────────
  {
    id: 'emp-nate-haws',
    name: 'Nathan Haws',
    rampName: 'Haws, Nathan',
    email: 'nate.haws@lineasolutions.com',
    companyGroup: 'Linea Solutions',
    businessUnit: 'Delivery',
    careerPath: 'Consultant',
    roleFamily: 'Business Analyst',
    practice: 'Pension',
    level: 'Associate Principal',
    title: 'Associate Principal Consultant & AI Researcher',
    location: 'US',
    resumeText: 'Nathan (Nate) Haws is an Associate Principal Consultant and AI Researcher at Linea Solutions with over 20 years in retirement plan administration. Currently serving as AI Strategic Advisor to SERS Ohio and working with CalSTRS on AI chatbot development. Past engagements include South Carolina PEBA, NYCPPF, and ERFC. Credentials: IIBA member, Six Sigma Black Belt, Certified Data Analyst, ChFC, CLU, OCEB2.',
    extractedSkills: JSON.stringify(['AI Strategy', 'Pension Administration', 'Business Analysis', 'Six Sigma Black Belt', 'Data Analysis', 'IIBA', 'ChFC', 'CLU', 'OCEB2', 'AI Chatbot Development', 'CalSTRS', 'SERS Ohio']),
  },
  {
    id: 'emp-paul-love',
    name: 'Paul Love',
    rampName: 'Love, Paul',
    email: 'paul.love@lineasolutions.com',
    companyGroup: 'Linea Solutions',
    businessUnit: 'Delivery',
    careerPath: 'Consultant',
    roleFamily: 'Consultant',
    practice: 'Pension',
    level: 'Senior Principal',
    title: 'Senior Principal Consultant',
    location: 'US',
    resumeText: 'Paul Love is a Senior Principal Consultant at Linea Solutions with deep expertise in pension administration system implementations. Leads complex engagements for large public retirement systems across the United States.',
    extractedSkills: JSON.stringify(['Pension Administration', 'System Implementation', 'Project Management', 'Business Analysis', 'Public Retirement Systems']),
  },
  {
    id: 'emp-angela-li',
    name: 'Angela Li',
    rampName: 'Li, Angela',
    email: 'angela.li@lineasolutions.com',
    companyGroup: 'Linea Solutions ULC',
    businessUnit: 'Delivery',
    careerPath: 'Consultant',
    roleFamily: 'Consultant',
    practice: 'Pension',
    level: 'Senior',
    title: 'Senior Pension Consultant & Innovation Lab Advisor',
    location: 'Canada',
    resumeText: 'Angela Li is a Senior Pension Consultant and Innovation Lab Advisor at Linea Solutions ULC with over 30 years in pension and benefits across Canada and the US. Previous roles include Pension Manager, Senior Benefits Consultant, and Director of Implementation Services. Advisor to Linea\'s internal innovation and AI initiatives.',
    extractedSkills: JSON.stringify(['Pension', 'Benefits Administration', 'Canada', 'Implementation', 'Innovation', 'AI Advisory', 'Change Management', 'Director-level Leadership']),
  },
  {
    id: 'emp-jessica-mahoney',
    name: 'Jessica Mahoney',
    rampName: 'Mahoney, Jessica',
    email: 'jessica.mahoney@lineasolutions.com',
    companyGroup: 'Linea Solutions',
    businessUnit: 'Delivery',
    careerPath: 'Consultant',
    roleFamily: 'Business Analyst',
    practice: 'CrossPractice',
    level: 'Associate Principal',
    title: 'Associate Principal Consultant',
    location: 'US',
    resumeText: 'Jessica Mahoney is an Associate Principal Consultant at Linea Solutions. Conference speaker at ATD 2024 (New Orleans) alongside Nicole Matthews; presented on talent development and organizational learning topics. Active participant in LIMRA Enrollment Technology Strategy Seminar.',
    extractedSkills: JSON.stringify(['Business Analysis', 'Training', 'ATD', 'Talent Development', 'Organizational Learning', 'Insurance', 'Pension', 'Facilitation']),
  },
  {
    id: 'emp-gerard-pappa',
    name: 'Gerard Pappa',
    rampName: 'Pappa, Gerard',
    email: 'gerard.pappa@lineasolutions.com',
    companyGroup: 'Linea Solutions',
    businessUnit: 'Delivery',
    careerPath: 'Consultant',
    roleFamily: 'Business Analyst',
    practice: 'CrossPractice',
    level: 'Senior',
    title: 'Senior Consultant — BPI / Lean Six Sigma Master Black Belt',
    location: 'US',
    resumeText: 'Gerard Pappa is a Senior Consultant at Linea Solutions specializing in Business Process Improvement (BPI) with Lean Six Sigma Master Black Belt certification. Leads process optimization engagements for pension and benefits organizations.',
    extractedSkills: JSON.stringify(['BPI', 'Lean Six Sigma', 'Master Black Belt', 'Business Process Improvement', 'Process Optimization', 'Pension', 'Benefits', 'Change Management']),
  },
  {
    id: 'emp-patricia-reed',
    name: 'Patricia Reed',
    rampName: 'Reed, Patricia',
    email: 'patricia.reed@lineasolutions.com',
    companyGroup: 'Linea Solutions',
    businessUnit: 'Delivery',
    careerPath: 'Consultant',
    roleFamily: 'Consultant',
    practice: 'Pension',
    level: 'Principal',
    title: 'Principal Consultant',
    location: 'US',
    resumeText: 'Patricia Reed is a Principal Consultant at Linea Solutions specializing in public pension system implementations and modernization projects.',
    extractedSkills: JSON.stringify(['Pension Administration', 'System Implementation', 'Business Analysis', 'Testing', 'Requirements Management']),
  },
  {
    id: 'emp-scott-larson',
    name: 'Scott Larson',
    rampName: 'Larson, Scott',
    email: 'scott.larson@lineasolutions.com',
    companyGroup: 'Linea Solutions',
    businessUnit: 'Delivery',
    careerPath: 'Consultant',
    roleFamily: 'Project Manager',
    practice: 'Workers Compensation',
    level: 'Principal',
    title: 'Principal Consultant',
    location: 'US',
    resumeText: 'Scott Larson is a Principal Consultant at Linea Solutions specializing in workers\' compensation and insurance system implementations.',
    extractedSkills: JSON.stringify(['Workers Compensation', 'Insurance', 'Project Management', 'System Implementation', 'Claims Administration']),
  },
  {
    id: 'emp-bonnie-marshall',
    name: 'Bonnie Marshall',
    rampName: 'Marshall, Bonnie',
    email: 'bonnie.marshall@lineasolutions.com',
    companyGroup: 'Linea Solutions ULC',
    businessUnit: 'Delivery',
    careerPath: 'Consultant',
    roleFamily: 'Business Analyst',
    practice: 'Pension',
    level: 'Associate Principal',
    title: 'Associate Principal Consultant',
    location: 'Canada',
    resumeText: 'Bonnie Marshall is an Associate Principal Consultant at Linea Solutions ULC, based in Canada. Specializes in pension administration and benefits system implementations for Canadian pension plans.',
    extractedSkills: JSON.stringify(['Pension', 'Benefits Administration', 'Business Analysis', 'Canada', 'System Implementation', 'Requirements Management']),
  },
  {
    id: 'emp-nicholas-zasada',
    name: 'Nicholas Zasada',
    rampName: 'Zasada, Nicholas',
    email: 'nicholas.zasada@lineasolutions.com',
    companyGroup: 'Linea Solutions',
    businessUnit: 'Delivery',
    careerPath: 'Consultant',
    roleFamily: 'Business Analyst',
    practice: 'Insurance',
    level: 'Associate Principal',
    title: 'Associate Principal Consultant',
    location: 'US',
    resumeText: 'Nicholas Zasada is an Associate Principal Consultant at Linea Solutions specializing in insurance and workers\' compensation engagements.',
    extractedSkills: JSON.stringify(['Insurance', 'Workers Compensation', 'Business Analysis', 'System Implementation', 'Requirements Management']),
  },
  {
    id: 'emp-stephanie-minton',
    name: 'Stephanie Minton',
    rampName: 'Minton, Stephanie',
    email: 'stephanie.minton@lineasolutions.com',
    companyGroup: 'Linea Solutions',
    businessUnit: 'Delivery',
    careerPath: 'Consultant',
    roleFamily: 'Business Analyst',
    practice: 'Pension',
    level: 'Associate Principal',
    title: 'Associate Principal Consultant',
    location: 'US',
    resumeText: 'Stephanie Minton is an Associate Principal Consultant at Linea Solutions specializing in pension administration system implementations and business process analysis.',
    extractedSkills: JSON.stringify(['Pension', 'Business Analysis', 'System Implementation', 'Process Analysis', 'Requirements Management']),
  },
  // ── Linea Secure ──────────────────────────────────────────────────────────
  {
    id: 'emp-peter-dewar',
    name: 'Peter Dewar',
    rampName: 'Dewar, Peter',
    email: 'peter.dewar@lineasecure.com',
    companyGroup: 'Linea Secure',
    businessUnit: 'Cyber',
    careerPath: 'Specialist',
    roleFamily: 'Cybersecurity',
    practice: 'Cybersecurity',
    level: 'Executive',
    title: 'President, Linea Secure',
    location: 'US',
    resumeText: 'Peter Dewar is President of Linea Secure with over 25 years in IT and cybersecurity; 14+ years focused on the pension sector. Creator of the Pension Cyber Security Framework (PCSF). Certifications: CISSP, CISA, CDPSE. Education: M.S. Information Systems (George Washington University), B.S. Information Systems (University of the District of Columbia). Certificates from Harvard Kennedy School of Government and Gartner CIO Academy. Conference speaker at NASRA Winter Meeting.',
    extractedSkills: JSON.stringify(['CISSP', 'CISA', 'CDPSE', 'Cybersecurity', 'Pension Cybersecurity', 'PCSF', 'NIST CSF', 'Risk Assessment', 'Incident Response', 'Cloud Security', 'CISO-as-a-Service', 'Penetration Testing']),
  },
  {
    id: 'emp-brian-colker',
    name: 'Brian Colker',
    rampName: 'Colker, Brian',
    email: 'brian.colker@lineasecure.com',
    companyGroup: 'Linea Secure',
    businessUnit: 'Cyber',
    careerPath: 'Specialist',
    roleFamily: 'Cybersecurity',
    practice: 'Cybersecurity',
    level: 'Principal',
    title: 'Principal, Linea Secure',
    location: 'US',
    resumeText: 'Brian Colker is a Principal at Linea Secure specializing in cybersecurity for pension and benefits organizations. Delivers penetration testing, risk assessments, and security advisory services.',
    extractedSkills: JSON.stringify(['Cybersecurity', 'Penetration Testing', 'Risk Assessment', 'Security Advisory', 'Pension Cybersecurity', 'NIST CSF']),
  },
  {
    id: 'emp-cassandra-kirchmeier',
    name: 'Cassandra Kirchmeier',
    rampName: 'Kirchmeier, Cassandra',
    email: 'cassandra.kirchmeier@lineasecure.com',
    companyGroup: 'Linea Secure',
    businessUnit: 'Cyber',
    careerPath: 'Specialist',
    roleFamily: 'Cybersecurity',
    practice: 'Cybersecurity',
    level: 'Senior',
    title: 'Senior Consultant, Linea Secure',
    location: 'Canada',
    resumeText: 'Cassandra Kirchmeier is a Senior Consultant at Linea Secure, based in Canada. Delivers cybersecurity assessments and advisory services for pension and benefits organizations. Conference speaker at NASRA Winter Meeting.',
    extractedSkills: JSON.stringify(['Cybersecurity', 'Security Assessment', 'Pension Cybersecurity', 'Canada', 'PCSF', 'Cloud Security', 'Risk Management']),
  },
  // ── ICON ──────────────────────────────────────────────────────────────────
  {
    id: 'emp-bradford-hodgson',
    name: 'Bradford Hodgson',
    rampName: 'Hodgson, Bradford',
    email: 'bradford.hodgson@lineasecure.com',
    companyGroup: 'Linea Secure',
    businessUnit: 'Cyber',
    careerPath: 'Management',
    roleFamily: 'Project Manager',
    practice: 'Cybersecurity',
    level: 'Manager',
    title: 'Manager of Operations, Linea Secure',
    location: 'US',
    resumeText: 'Bradford Hodgson is Manager of Operations at Linea Secure, overseeing day-to-day delivery operations for cybersecurity engagements and internal business operations.',
    extractedSkills: JSON.stringify(['Operations Management', 'Cybersecurity', 'Project Management', 'Delivery Management', 'Business Operations']),
  },
  {
    id: 'emp-dana-schappert',
    name: 'Dana Schappert Quaynor',
    rampName: 'Schappert Quaynor, Dana',
    email: 'dana.schappert@lineasolutions.com',
    companyGroup: 'Linea Solutions',
    businessUnit: 'Delivery',
    careerPath: 'Consultant',
    roleFamily: 'Consultant',
    practice: 'Pension',
    level: 'Associate Principal',
    title: 'Associate Principal Consultant',
    location: 'US',
    resumeText: 'Dana Schappert Quaynor is an Associate Principal Consultant at Linea Solutions specializing in pension and benefits administration implementations.',
    extractedSkills: JSON.stringify(['Pension', 'Benefits Administration', 'Business Analysis', 'System Implementation', 'Change Management']),
  },
  {
    id: 'emp-fred-webster',
    name: 'Fred Webster',
    rampName: 'Webster, Fred',
    email: 'fred.webster@lineasolutions.com',
    companyGroup: 'Linea Solutions',
    businessUnit: 'Sales & Business Development',
    careerPath: 'Management',
    roleFamily: 'Business Development',
    practice: 'Workers Compensation',
    level: 'Senior',
    title: 'Senior Consultant, Workers\' Compensation Business Development',
    location: 'US',
    resumeText: 'Fred Webster focuses on business development for Linea Solutions\' Workers\' Compensation practice, identifying and developing new client relationships in the workers\' comp sector.',
    extractedSkills: JSON.stringify(['Workers Compensation', 'Business Development', 'Client Relations', 'Sales', 'Insurance']),
  },
];

// ─── Real Projects (publicly confirmed engagements) ───────────────────────────

const REAL_PROJECTS = [
  {
    id: 'proj-calstrs-ai',
    rampProjectCode: 'PRJ-001001',
    name: 'CalSTRS — AI Deployment & System Implementation Support',
    clientId: 'client-calstrs',
    clientName: 'California State Teachers\' Retirement System (CalSTRS)',
    accountExecutive: 'Lynch, Kevin',
    engagementManager: 'Haws, Nathan',
    engagementClass: 'Client',
    industryTag: 'pension',
    scopeCategories: JSON.stringify(['implementation', 'ai_strategy']),
    status: 'In Progress',
    description: 'Linea Solutions is supporting CalSTRS with AI chatbot development and system implementation. Nathan Haws is the primary engagement lead. CalSTRS is one of the largest public pension funds in the US with approximately $300 billion in assets serving California teachers.',
    currentPhase: 'Implementation',
    startDate: new Date('2023-07-01'),
  },
  {
    id: 'proj-sers-ai',
    rampProjectCode: 'PRJ-001002',
    name: 'SERS Ohio — AI Strategy Advisory',
    clientId: 'client-sers-ohio',
    clientName: 'School Employees Retirement System of Ohio (SERS)',
    accountExecutive: 'Lynch, Kevin',
    engagementManager: 'Haws, Nathan',
    engagementClass: 'Client',
    industryTag: 'pension',
    scopeCategories: JSON.stringify(['ai_strategy', 'assessment']),
    status: 'In Progress',
    description: 'Nathan Haws serving as AI Strategic Advisor to SERS Ohio, guiding the retirement system\'s AI adoption strategy, vendor evaluation, and responsible AI governance framework.',
    currentPhase: 'Requirements',
    startDate: new Date('2024-01-15'),
  },
  {
    id: 'proj-vrs-data',
    rampProjectCode: 'PRJ-001003',
    name: 'Virginia Retirement System — Data Conversion & Migration',
    clientId: 'client-vrs',
    clientName: 'Virginia Retirement System (VRS)',
    accountExecutive: 'Tagawa, Akio',
    engagementManager: 'Love, Paul',
    engagementClass: 'ICON',
    industryTag: 'pension',
    scopeCategories: JSON.stringify(['data_conversion']),
    status: 'Completed',
    description: 'Data profiling, conversion, reconciliation, and migration engagement for VRS via ICON Integration & Design. Supported the transition from legacy administration systems.',
    currentPhase: 'Support',
    startDate: new Date('2022-03-01'),
    endDate: new Date('2023-12-31'),
  },
  {
    id: 'proj-ucrs-data',
    rampProjectCode: 'PRJ-001004',
    name: 'University of California Retirement System — Data Migration',
    clientId: 'client-ucrs',
    clientName: 'University of California Retirement System (UCRS)',
    accountExecutive: 'Tagawa, Akio',
    engagementManager: 'Love, Paul',
    engagementClass: 'ICON',
    industryTag: 'pension',
    scopeCategories: JSON.stringify(['data_conversion']),
    status: 'Completed',
    description: 'Data profiling, cleansing, and migration project for the University of California\'s multi-campus retirement system via ICON.',
    currentPhase: 'Support',
    startDate: new Date('2022-09-01'),
    endDate: new Date('2024-06-30'),
  },
  {
    id: 'proj-nycppf-impl',
    rampProjectCode: 'PRJ-001005',
    name: 'New York City Police Pension Fund — System Implementation',
    clientId: 'client-nycppf',
    clientName: 'New York City Police Pension Fund (NYCPPF)',
    accountExecutive: 'Lynch, Kevin',
    engagementManager: 'Haws, Nathan',
    engagementClass: 'Client',
    industryTag: 'pension',
    scopeCategories: JSON.stringify(['implementation']),
    status: 'Completed',
    description: 'Pension administration system implementation support for one of New York City\'s largest uniformed services pension funds.',
    currentPhase: 'Support',
    startDate: new Date('2020-06-01'),
    endDate: new Date('2023-03-31'),
  },
  {
    id: 'proj-sc-peba-impl',
    rampProjectCode: 'PRJ-001006',
    name: 'South Carolina PEBA — System Implementation',
    clientId: 'client-sc-peba',
    clientName: 'South Carolina Public Employee Benefit Authority (PEBA)',
    accountExecutive: 'Lynch, Kevin',
    engagementManager: 'Zierath, Kim',
    engagementClass: 'Client',
    industryTag: 'pension',
    scopeCategories: JSON.stringify(['implementation', 'ocm']),
    status: 'Completed',
    description: 'Core pension administration system replacement for South Carolina\'s statewide public employee benefit authority. Includes business analysis, testing, OCM, and training.',
    currentPhase: 'Support',
    startDate: new Date('2019-01-15'),
    endDate: new Date('2022-12-31'),
  },
  {
    id: 'proj-barbados-social',
    rampProjectCode: 'PRJ-001007',
    name: 'Barbados National Insurance — Social Program Modernization',
    clientId: 'client-barbados-nlc',
    clientName: 'Barbados National Insurance Scheme',
    accountExecutive: 'Tiggelaar, Lon',
    engagementManager: 'Kennedy, Vickie',
    engagementClass: 'Client',
    industryTag: 'workers_comp',
    scopeCategories: JSON.stringify(['assessment', 'implementation', 'roadmap']),
    status: 'In Progress',
    description: 'International expansion engagement supporting Barbados in the modernization of social program and workers\' compensation administration. Linea\'s first Caribbean engagement.',
    currentPhase: 'Planning',
    startDate: new Date('2024-06-01'),
  },
  {
    id: 'proj-ipers-data',
    rampProjectCode: 'PRJ-001008',
    name: 'Iowa PERS — Data Quality & Conversion',
    clientId: 'client-ipers',
    clientName: 'Iowa Public Employees\' Retirement System (IPERS)',
    accountExecutive: 'Tagawa, Akio',
    engagementManager: 'Love, Paul',
    engagementClass: 'ICON',
    industryTag: 'pension',
    scopeCategories: JSON.stringify(['data_conversion']),
    status: 'Completed',
    description: 'Data quality assessment and conversion project for Iowa\'s statewide public employee retirement system via ICON Integration & Design.',
    currentPhase: 'Support',
    startDate: new Date('2021-04-01'),
    endDate: new Date('2023-06-30'),
  },
  {
    id: 'proj-linea-secure-pcsf',
    rampProjectCode: 'PRJ-001009',
    name: 'Linea Secure — Pension Cyber Security Framework (PCSF) Rollout',
    clientId: 'client-calstrs',
    clientName: 'California State Teachers\' Retirement System (CalSTRS)',
    accountExecutive: 'Haws, Bryce',
    engagementManager: 'Dewar, Peter',
    engagementClass: 'Cyber',
    industryTag: 'cybersecurity',
    scopeCategories: JSON.stringify(['cybersecurity', 'assessment']),
    status: 'In Progress',
    description: 'Deploying the Pension Cyber Security Framework (PCSF) — Linea Secure\'s proprietary cybersecurity standard built on the NIST CSF — for major pension clients. Includes risk assessments, penetration testing, and CISO-as-a-Service.',
    currentPhase: 'Implementation',
    startDate: new Date('2023-01-01'),
  },
];

// ─── Allocations: key consultants → their active projects ────────────────────

const REAL_ALLOCATIONS = [
  { employeeId: 'emp-nate-haws',           projectId: 'proj-calstrs-ai',         allocationPercent: 50, roleOnProject: 'AI Implementation Lead', assignmentCode: 'AS-10001', assignmentDetail: 'Haws, Nathan-CalSTRS AI (01/01/24-12/31/25)', startDate: '2024-01-01', endDate: '2025-12-31' },
  { employeeId: 'emp-nate-haws',           projectId: 'proj-sers-ai',            allocationPercent: 40, roleOnProject: 'AI Strategic Advisor',    assignmentCode: 'AS-10002', assignmentDetail: 'Haws, Nathan-SERS AI Advisory (01/15/24-12/31/25)', startDate: '2024-01-15', endDate: '2025-12-31' },
  { employeeId: 'emp-kim-zierath',         projectId: 'proj-sc-peba-impl',       allocationPercent: 80, roleOnProject: 'Engagement Manager',       assignmentCode: 'AS-10003', assignmentDetail: 'Zierath, Kim-SC PEBA Impl (01/15/19-12/31/22)', startDate: '2019-01-15', endDate: '2022-12-31' },
  { employeeId: 'emp-paul-love',           projectId: 'proj-vrs-data',           allocationPercent: 60, roleOnProject: 'Senior Delivery Lead',     assignmentCode: 'AS-10004', assignmentDetail: 'Love, Paul-VRS Data (03/01/22-12/31/23)', startDate: '2022-03-01', endDate: '2023-12-31' },
  { employeeId: 'emp-paul-love',           projectId: 'proj-ucrs-data',          allocationPercent: 40, roleOnProject: 'Senior Delivery Lead',     assignmentCode: 'AS-10005', assignmentDetail: 'Love, Paul-UCRS Data (09/01/22-06/30/24)', startDate: '2022-09-01', endDate: '2024-06-30' },
  { employeeId: 'emp-vickie-kennedy',      projectId: 'proj-barbados-social',    allocationPercent: 60, roleOnProject: 'Engagement Manager',        assignmentCode: 'AS-10006', assignmentDetail: 'Kennedy, Vickie-Barbados Social (06/01/24-12/31/25)', startDate: '2024-06-01', endDate: '2025-12-31' },
  { employeeId: 'emp-ryan-guppy',          projectId: 'proj-barbados-social',    allocationPercent: 40, roleOnProject: 'WDP Advisor',               assignmentCode: 'AS-10007', assignmentDetail: 'Guppy, Ryan-Barbados Social (06/01/24-12/31/25)', startDate: '2024-06-01', endDate: '2025-12-31' },
  { employeeId: 'emp-jessica-mahoney',     projectId: 'proj-calstrs-ai',         allocationPercent: 50, roleOnProject: 'Senior BA — AI',            assignmentCode: 'AS-10008', assignmentDetail: 'Mahoney, Jessica-CalSTRS AI (01/01/24-12/31/25)', startDate: '2024-01-01', endDate: '2025-12-31' },
  { employeeId: 'emp-peter-dewar',         projectId: 'proj-linea-secure-pcsf',  allocationPercent: 60, roleOnProject: 'Program Lead — PCSF',       assignmentCode: 'AS-10009', assignmentDetail: 'Dewar, Peter-PCSF Rollout (01/01/23-12/31/25)', startDate: '2023-01-01', endDate: '2025-12-31' },
  { employeeId: 'emp-cassandra-kirchmeier',projectId: 'proj-linea-secure-pcsf',  allocationPercent: 80, roleOnProject: 'Sr. Cyber Consultant',      assignmentCode: 'AS-10010', assignmentDetail: 'Kirchmeier, Cassandra-PCSF Rollout (01/01/23-12/31/25)', startDate: '2023-01-01', endDate: '2025-12-31' },
  { employeeId: 'emp-angela-li',           projectId: 'proj-sers-ai',            allocationPercent: 30, roleOnProject: 'Senior Pension Advisor',    assignmentCode: 'AS-10011', assignmentDetail: 'Li, Angela-SERS AI Advisory (01/15/24-12/31/25)', startDate: '2024-01-15', endDate: '2025-12-31' },
  { employeeId: 'emp-patricia-reed',       projectId: 'proj-nycppf-impl',        allocationPercent: 80, roleOnProject: 'Principal Consultant',      assignmentCode: 'AS-10012', assignmentDetail: 'Reed, Patricia-NYCPPF Impl (06/01/20-03/31/23)', startDate: '2020-06-01', endDate: '2023-03-31' },
  { employeeId: 'emp-vincent-houle',       projectId: 'proj-calstrs-ai',         allocationPercent: 30, roleOnProject: 'Resource Coordinator',      assignmentCode: 'AS-10013', assignmentDetail: 'Houle, Vincent-CalSTRS AI (01/01/24-12/31/25)', startDate: '2024-01-01', endDate: '2025-12-31' },
  { employeeId: 'emp-gerard-pappa',        projectId: 'proj-barbados-social',    allocationPercent: 50, roleOnProject: 'BPI / LSS Lead',             assignmentCode: 'AS-10014', assignmentDetail: 'Pappa, Gerard-Barbados Social (06/01/24-12/31/25)', startDate: '2024-06-01', endDate: '2025-12-31' },
  { employeeId: 'emp-lon-tiggelaar',       projectId: 'proj-barbados-social',    allocationPercent: 20, roleOnProject: 'Account Executive Oversight', assignmentCode: 'AS-10015', assignmentDetail: 'Tiggelaar, Lon-Barbados Social (06/01/24-12/31/25)', startDate: '2024-06-01', endDate: '2025-12-31' },
];

// ─── POST handler — upsert everything ─────────────────────────────────────────

export async function POST(req: NextRequest) {
  const results = { clients: 0, employees: 0, projects: 0, allocations: 0, errors: [] as string[] };

  // 1. Upsert clients — stored as ClientNote (no separate Client model; clients derive from project.clientName)
  for (const c of REAL_CLIENTS) {
    try {
      await prisma.clientNote.upsert({
        where: { clientId: c.id },
        update: { clientName: c.name, notes: `${c.industry} | ${(c as any).location || ''} | ${(c as any).notes || ''}` },
        create: {
          clientId: c.id,
          clientName: c.name,
          notes: `${c.industry} | ${(c as any).location || ''} | ${(c as any).notes || ''}`,
        },
      });
      results.clients++;
    } catch (e: any) {
      results.errors.push(`Client ${c.name}: ${e.message}`);
    }
  }

  // 2. Upsert employees
  for (const emp of REAL_EMPLOYEES) {
    try {
      await prisma.employee.upsert({
        where: { id: emp.id },
        update: {
          name: emp.name,
          title: emp.title,
          level: emp.level,
          practice: emp.practice,
          companyGroup: emp.companyGroup,
          businessUnit: emp.businessUnit,
          location: emp.location,
        },
        create: {
          id: emp.id,
          name: emp.name,
          rampName: emp.rampName,
          email: emp.email,
          companyGroup: emp.companyGroup,
          businessUnit: emp.businessUnit,
          careerPath: emp.careerPath,
          roleFamily: emp.roleFamily,
          practice: emp.practice,
          level: emp.level,
          title: emp.title,
          location: emp.location,
          resumeText: emp.resumeText,
          extractedSkills: emp.extractedSkills,
        },
      });
      results.employees++;
    } catch (e: any) {
      results.errors.push(`Employee ${emp.name}: ${e.message}`);
    }
  }

  // 3. Upsert projects
  for (const proj of REAL_PROJECTS) {
    try {
      await prisma.project.upsert({
        where: { id: proj.id },
        update: {
          name: proj.name,
          status: proj.status,
          description: proj.description,
          currentPhase: proj.currentPhase,
        },
        create: {
          id: proj.id,
          rampProjectCode: proj.rampProjectCode,
          name: proj.name,
          clientId: proj.clientId,
          clientName: proj.clientName,
          accountExecutive: proj.accountExecutive,
          engagementManager: proj.engagementManager,
          engagementClass: proj.engagementClass,
          industryTag: proj.industryTag,
          scopeCategories: proj.scopeCategories,
          status: proj.status,
          description: proj.description,
          currentPhase: proj.currentPhase,
          startDate: proj.startDate,
          endDate: (proj as any).endDate,
        },
      });
      results.projects++;
    } catch (e: any) {
      results.errors.push(`Project ${proj.name}: ${e.message}`);
    }
  }

  // 4. Upsert allocations
  for (const alloc of REAL_ALLOCATIONS) {
    try {
      // Check employee and project exist
      const empExists = await prisma.employee.findUnique({ where: { id: alloc.employeeId } });
      const projExists = await prisma.project.findUnique({ where: { id: alloc.projectId } });
      if (!empExists || !projExists) {
        results.errors.push(`Allocation skipped: ${alloc.employeeId} → ${alloc.projectId} (emp: ${!!empExists}, proj: ${!!projExists})`);
        continue;
      }
      // Check if allocation already exists
      const existing = await prisma.allocation.findFirst({
        where: { employeeId: alloc.employeeId, projectId: alloc.projectId },
      });
      if (!existing) {
        await prisma.allocation.create({
          data: {
            employeeId: alloc.employeeId,
            projectId: alloc.projectId,
            allocationPercent: alloc.allocationPercent,
            roleOnProject: alloc.roleOnProject,
            assignmentCode: alloc.assignmentCode,
            assignmentDetail: alloc.assignmentDetail,
            startDate: new Date(alloc.startDate),
            endDate: new Date(alloc.endDate),
          },
        });
      }
      results.allocations++;
    } catch (e: any) {
      results.errors.push(`Allocation ${alloc.employeeId}: ${e.message}`);
    }
  }

  return NextResponse.json({
    message: 'Linea Solutions real data seeded successfully',
    ...results,
  });
}
